{
 "title": "JMeter",
 "description": "eXo overview",
 "tags": [ "jmeter" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,30m,1h,12,1d" },
   { "name": "exoplatform_infra_ds", "query": "influxdb" },
   { "name": "monitoring_infra_ds", "query": "influxdb" },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "SHOW TAG VALUES FROM \"jvm_gc\" WITH KEY = \"host\""
   },
   {
    "name": "memory_pool",
    "label": "Mem Pool",
    "query": "SHOW TAG VALUES FROM \"jvm_memory_pool\" WITH KEY = \"typeName\" WHERE \"host\"='$hosts'"
   },
   { "name": "DS_MONITORING_JMETER", "query": "monitoring_jmeter" }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "server (node)",
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "content": "<center><b><u>$hosts ($nodes)</u></b></center>"
  },
  {
   "title": "SYS CX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "full gc count" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=GarbageCollector,name=PS MarkSweep"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Load average - $hosts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_system",
     "select": [
      [
       { "params": [ "SystemLoadAverage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Load average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - $hosts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_system",
     "select": [
      [
       { "params": [ "TotalPhysicalMemorySize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "FreePhysicalMemorySize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap - $hosts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_system",
     "select": [
      [
       { "params": [ "TotalSwapSpaceSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "FreeSwapSpaceSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Files - $hosts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_system",
     "select": [
      [
       { "params": [ "MaxFileDescriptorCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "OpenFileDescriptorCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "open" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads ($hosts)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "repeat": "hosts",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_threads",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "number" ], "type": "alias" }
      ],
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "daemon" ], "type": "alias" }
      ],
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "peak" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalStartedThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "creation rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "JVM Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapMemoryUsage_committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapMemoryUsage_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used (max)" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapMemoryUsage_committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed (max)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem Pool $memory_pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "repeat": "memory_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_pool",
     "select": [
      [
       { "params": [ "Usage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "Usage_committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "Usage_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used (max)" ], "type": "alias" }
      ],
      [
       { "params": [ "Usage_committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed (max)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" },
      {
       "condition": "AND",
       "key": "typeName",
       "operator": "=~",
       "value": "/^type=MemoryPool,name=$memory_pool$/"
      }
     ]
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "G1 Young Gen (non blocking) - $hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jvm_gc",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "count" ], "type": "alias" }
      ],
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "time" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=GarbageCollector,name=G1 Young Generation"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "G1 Old Gen (blocking) - $hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jvm_gc",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "count" ], "type": "alias" }
      ],
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "time" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=GarbageCollector,name=G1 Old Generation"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  }
 ]
}