{
 "title": "Elasticsearch",
 "description": "Elastic Search monitoring dashboard",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" },
   { "name": "infra", "label": "Infrastructure", "query": "exo" },
   { "name": "monitoring_infra_ds", "query": "influxdb" },
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"elasticsearch_process\" WITH KEY = \"cluster_name\""
   },
   {
    "name": "node",
    "query": "SHOW TAG VALUES FROM \"elasticsearch_process\" WITH KEY = \"node_name\" WHERE \"cluster_name\"='$cluster'"
   },
   {
    "name": "hosts",
    "query": "SHOW TAG VALUES FROM \"elasticsearch_process\" WITH KEY = \"host\" WHERE \"cluster_name\"='$cluster'"
   },
   {
    "name": "thread_pools",
    "label": "ES Thread Pools",
    "query": "bulk,fetch_shard_started,fetch_shard_store,flush,force_merge,generic,get,index,listener,management,refresh,percolate,search,snapshot,warmer,suggest,watcher"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_process",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_process",
     "select": [
      [
       { "params": [ "mem_total_virtual_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap % usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name / $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cpu (max)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Docs count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "docs" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Docs deleted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "docs_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "docs" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Store size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Store latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "store_throttle_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Search request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "search_query_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "query" ], "type": "alias" }
      ],
      [
       { "params": [ "search_scroll_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "scroll" ], "type": "alias" }
      ],
      [
       { "params": [ "search_fetch_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "fetch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search query time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "search_query_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "query" ], "type": "alias" }
      ],
      [
       { "params": [ "search_fetch_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "fetch" ], "type": "alias" }
      ],
      [
       { "params": [ "search_scroll_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "scroll" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Indexation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Indexing request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "indexing_index_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "index" ], "type": "alias" }
      ],
      [
       { "params": [ "indexing_delete_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "delete" ], "type": "alias" }
      ],
      [
       { "params": [ "indexing_noop_update_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "noop update" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       {
        "params": [
         "indexing_throttle_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "throttle" ], "type": "alias" }
      ],
      [
       { "params": [ "indexing_index_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "index" ], "type": "alias" }
      ],
      [
       { "params": [ "indexing_delete_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "delete" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Indexing fail",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "indexing_index_failed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "failed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Merge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Merge rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "merges_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "merges" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Merge size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "merges_total_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "merges" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "JVM ($hosts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "hosts" },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "threads_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count" ], "type": "alias" }
      ],
      [
       { "params": [ "threads_peak_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "peak count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_committed_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Non Heap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       {
        "params": [
         "mem_non_heap_committed_in_bytes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_non_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "JVM ($hosts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "threads_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count" ], "type": "alias" }
      ],
      [
       { "params": [ "threads_peak_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "peak count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_committed_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Non Heap usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       {
        "params": [
         "mem_non_heap_committed_in_bytes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "committed" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_non_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "JVM ES Thread Pools ($hosts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "hosts" },
  {
   "title": "Thread Pool - search",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "search_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "search_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "search_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "search_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "search_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "search_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - bulk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "bulk_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - fetch_shard_started",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "fetch_shard_started_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - flush",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "flush_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - generic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "generic_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - force_merge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "force_merge_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - index",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "index_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "index_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "index_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "index_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "index_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "index_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - management",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "management_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "management_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "management_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "management_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "management_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "management_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - get",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "get_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "get_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "get_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "get_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "get_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "get_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - snapshot",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "snapshot_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - refresh",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "refresh_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - listener",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "listener_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - percolate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "percolate_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - warmer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "warmer_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - suggest",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "suggest_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - fetch_shard_store",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "fetch_shard_store_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - watcher",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "watcher_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "JVM ES Thread Pools ($hosts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Thread Pool - search",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "search_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "search_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "search_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "search_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "search_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "search_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - bulk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "bulk_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "bulk_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - fetch_shard_started",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "fetch_shard_started_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - flush",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "flush_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - generic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "generic_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - force_merge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "force_merge_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - index",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "index_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "index_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "index_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "index_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "index_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "index_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - management",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "management_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "management_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "management_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "management_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "management_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "management_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - get",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "get_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "get_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "get_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "get_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "get_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "get_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - snapshot",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "snapshot_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "snapshot_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - refresh",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "refresh_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - listener",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "listener_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - percolate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "percolate_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "percolate_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - warmer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "warmer_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "warmer_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - suggest",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "suggest_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "suggest_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - fetch_shard_store",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "fetch_shard_store_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - watcher",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "watcher_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "completed" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rejected" ], "type": "alias" }
      ],
      [
       { "params": [ "watcher_largest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "largests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Requests in / out ($node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "repeat": "node",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "select": [
      [
       { "params": [ "rx_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests in / out ($node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "select": [
      [
       { "params": [ "rx_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}